# Generated by Django 3.0.4 on 2020-04-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ifstaffrole',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('ACADEMIC', 'Academic Dept.'), ('EXAM CELL', 'Exam cell')], max_length=20, null=True),
        ),
    ]
