# Generated by Django 3.0.5 on 2020-04-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_ifstaffrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parents',
            field=models.BooleanField(default=False),
        ),
    ]
