# Generated by Django 3.0.5 on 2020-04-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_ktclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktclass',
            name='classid',
            field=models.CharField(default='h', max_length=16),
            preserve_default=False,
        ),
    ]
