# Generated by Django 3.0.5 on 2020-05-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_studenteditprofilerequest_addedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenteditprofilerequest',
            name='acknowledge',
            field=models.BooleanField(default=False),
        ),
    ]
