# Generated by Django 3.0.4 on 2020-05-01 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0004_auto_20200501_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolledclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.klass'),
        ),
    ]
