# Generated by Django 3.0.5 on 2020-05-01 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='examform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('sem', models.CharField(max_length=2)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('open_till', models.DateField()),
                ('is_kt', models.BooleanField(default=False)),
                ('fee', models.IntegerField()),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.collegestaff')),
                ('klass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.klass')),
                ('ktclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.ktclass')),
            ],
        ),
        migrations.CreateModel(
            name='examformFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('pervioushalltickit_no', models.CharField(blank=True, max_length=16, null=True)),
                ('feerecipt', models.ImageField(blank=True, null=True, upload_to='')),
                ('fee', models.IntegerField()),
                ('filled', models.BooleanField(default=False)),
                ('examform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examform.examform')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.student')),
            ],
        ),
    ]
