# Generated by Django 3.0.5 on 2020-04-30 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0003_ktclass_classid'),
    ]

    operations = [
        migrations.CreateModel(
            name='examform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=2)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('open_till', models.DateField()),
                ('is_kt', models.BooleanField(default=False)),
                ('pervioushalltickit_no', models.CharField(max_length=16)),
                ('feerecipt', models.ImageField(upload_to='')),
                ('fee', models.IntegerField()),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.collegestaff')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.klass')),
            ],
        ),
    ]
