# Generated by Django 3.0.5 on 2020-05-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examformfill',
            name='fee',
        ),
    ]
