# Generated by Django 3.0.4 on 2020-05-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_auto_20200501_1937'),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='displaytoclasses',
            field=models.ManyToManyField(blank=True, null=True, to='academic.klass'),
        ),
    ]
