# Generated by Django 3.0.4 on 2020-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_auto_20200501_1937'),
        ('notice', '0002_auto_20200501_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='displaytoclasses',
            field=models.ManyToManyField(blank=True, to='academic.klass'),
        ),
    ]
