# Generated by Django 3.0.4 on 2020-05-01 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20200501_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='added_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
