# Generated by Django 3.0.5 on 2020-04-30 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0003_ktclass_classid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('marksheet12', models.ImageField(upload_to='')),
                ('marksheet34', models.ImageField(upload_to='')),
                ('marksheet56', models.ImageField(upload_to='')),
                ('marksheet78', models.ImageField(blank=True, null=True, upload_to='')),
                ('feerecipt', models.ImageField(upload_to='')),
                ('application', models.ImageField(upload_to='')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic.student')),
            ],
        ),
    ]
